### ISSUE TITLE
Generate world

### ISSUE THREAD

**Issue by szalkusz** [kozosjavak/asteroidmining#188]

**Comment by ventt** [comment]
800x800as vilagot kene legeneralni egy nagyjabol egyenletes de randlm eloszlasu nyersanyaggal, van 20% random generator fgv. Adott a ☀️ amit kezdeskent en kozepre raknek es ugye 5 telepes random oket is leszorni aszteroidakra es ugye sztem 2 vagy 3 ufo. Fontos lenne az egyenletes eloszlas mert ha nincs akkor beszorulhat a nap ugye a collison detection altal(ja igen ezt lehet hasznalni generalasnal is) es miutan legeneralodott a vilag indul a life cycle ugye ott mar adott a szomszed ujrafelfedezes.
